### ISSUE TITLE
gm update-cache crashes nushell

### ISSUE THREAD

**Issue by stormasm** [amtoine/nu-git-manager#40] opened 2023-10-26 22:26 UTC
This is what initially happens when you bring nu-git-manager out of the box...

In other words the first time installing it...

I started off by running

```rust
gm clone https://github.com/amtoine/nu-git-manager
```

And then got the message that "cache not found"

So I went ahead and ran the command

```rust
gm update-cache
```

And this is what happend --- nushell crashed and paniced with this error message

```rust
updating cache... Error:   × Deprecated option
    ╭─[/Users/ma/j/tmp17/nu-git-manager/nu-git-manager/fs/store.nu:38:1]
 38 │     cd (get-repo-store-path)
 39 │     let heads: list<string> = glob "**/HEAD" --not [
    ·                               ──┬─
    ·                                 ╰── `glob --not {list<string>}` is deprecated and will be removed in 0.88.
 40 │             **/.git/**/refs/remotes/**/HEAD,
    ╰────
  help: Please use `glob --exclude {list<string>}` instead.


thread 'main' panicked at 'attempt to add with overflow', crates/nu-command/src/filters/range.rs:108:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This happens on both the main branch and the release of nushell 0.86

Both error out in the exact same spot...

https://github.com/nushell/nushell/blob/main/crates/nu-command/src/filters/range.rs#L108

**Comment by amtoine** [comment] 2023-10-27 08:59
@stormasm 
thanks for reporting this :pray: 

can you confirm you can reproduce, after updating `nu-git-manager`, when following the steps below? :innocent: 
1. define the reproduction environment
```nushell
const REPRO_ENV = { GIT_REPOS_HOME: /tmp/repos/, GIT_REPOS_CACHE: /tmp/repos.cache }
```
2. clean the repro 
```nushell
with-env $REPRO_ENV {
    gm status | select root.path cache.path | values | each {
        if ($in | path exists) { rm --recursive --force --verbose $in }
    }
}
```
3. clone a repo
```nushell
> with-env $REPRO_ENV { gm clone https://github.com/amtoine/nu-git-manager }
Cloning into '/tmp/repos/github.com/amtoine/nu-git-manager'...
remote: Enumerating objects: 513, done.
remote: Counting objects: 100% (186/186), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 513 (delta 109), reused 133 (delta 81), pack-reused 327
Receiving objects: 100% (513/513), 125.76 KiB | 2.37 MiB/s, done.
Resolving deltas: 100% (235/235), done.
Error:   × cache_not_found:
  │ please run `gm update-cache` to create the cache
```
4. update the cache as proposed
```nushell
> with-env $REPRO_ENV { gm update-cache }
updating cache... done
```
> **Note**
> there a deprecation warning from Nushell in the output of the command above, but that's expected and can be ommitted
5. it works on my side
```nushell
> with-env $REPRO_ENV { gm list }
─┬─────────────────────────────────
0│github.com/amtoine/nu-git-manager
─┴─────────────────────────────────
```

**Comment by stormasm** [comment] 2023-10-27 18:30
@amtoine I followed the above steps as you proposed and here is what happens...

bottom line is that it crashes nushell 👎 

```rust
~/j/tmp17/nu-git-manager> use nu-git-manager *
~/j/tmp17/nu-git-manager> const REPRO_ENV = { GIT_REPOS_HOME: /tmp/repos/, GIT_REPOS_CACHE: /tmp/repos.cache }
~/j/tmp17/nu-git-manager> with-env $REPRO_ENV {
:::     gm status | select root.path cache.path | values | each {
:::         if ($in | path exists) { rm --recursive --force --verbose $in }
:::     }
::: }
╭────────────╮
│ empty list │
╰────────────╯
~/j/tmp17/nu-git-manager> with-env $REPRO_ENV { gm clone https://github.com/amtoine/nu-git-manager }
Cloning into '/tmp/repos/github.com/amtoine/nu-git-manager'...
remote: Enumerating objects: 574, done.
remote: Counting objects: 100% (247/247), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 574 (delta 139), reused 210 (delta 115), pack-reused 327
Receiving objects: 100% (574/574), 136.27 KiB | 2.57 MiB/s, done.
Resolving deltas: 100% (265/265), done.
Error:   × cache_not_found:
  │ please run `gm update-cache` to create the cache


~/j/tmp17/nu-git-manager> with-env $REPRO_ENV { gm update-cache }
updating cache... Error:   × Deprecated option
    ╭─[/Users/ma/j/tmp17/nu-git-manager/nu-git-manager/fs/store.nu:41:1]
 41 │     cd (get-repo-store-path)
 42 │     let heads: list<string> = glob "**/HEAD" --not [
    ·                               ──┬─
    ·                                 ╰── `glob --not {list<string>}` is deprecated and will be removed in 0.88.
 43 │             **/.git/**/refs/remotes/**/HEAD,
    ╰────
  help: Please use `glob --exclude {list<string>}` instead.


thread 'main' panicked at 'attempt to add with overflow', crates/nu-command/src/filters/range.rs:108:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by melMass** [comment] 2023-10-27 19:10
Maybe the exclude/not change is more than a future deprecation and is already defunct?

I will try to repro on windows.

**Comment by stormasm** [comment] 2023-10-28 01:42
@melMass I am seeing this bug on my mac Apple M1 Pro Ventura.  @amtoine told me you had a mac (I think) so I would be curious to know if you are seeing the bug as well...
Thanks ! 😄

**Comment by melMass** [comment] 2023-10-28 07:11
> @melMass I am seeing this bug on my mac Apple M1 Pro Ventura.  @amtoine told me you had a mac (I think) so I would be curious to know if you are seeing the bug as well...
> 
> Thanks ! 😄 

Yep I will properly test it out tomorrow I have the exact same config.
But I think that a panic should never happen so I wonder if this did not reveal a "bug" in nu itself

**Comment by amtoine** [comment] 2023-10-28 11:36
@stormasm thanks for checking with the blank `$REPRO_ENV` :pray: 

@melMass
> Maybe the exclude/not change is more than a future deprecation and is already defunct?


>
i don't think this is an issue with the deprecation of `glob --not` => i cannot reproduce this on my machine yet i see the deprecation warning

> Yep I will properly test it out tomorrow I have the exact same config.
>
amazing :pray: 

> But I think that a panic should never happen so I wonder if this did not reveal a "bug" in nu itself
>
yup, i think this is a bug from Nushell, we don't even use `range` at all :eyes:

**Comment by stormasm** [comment] 2023-10-28 15:34
@melMass Thanks for testing it out when you get some free time...

If we can get confirmation that it happens on your mac as well then we will have more information
and I will know its just not my machine or some weird configuration on my machine.

**Comment by melMass** [comment] 2023-10-30 12:36
> I started off by running
> 
> ```rust
> gm clone https://github.com/amtoine/nu-git-manager
> ```

Is this an example after having done all the install steps of gm and you used the gm repo url as an example? 
I don't really understand the repro there.

For me after following the install instructions on mac I don't even get the `update-cache` command exposed:

<img width="676" alt="image" src="https://github.com/amtoine/nu-git-manager/assets/7041726/8e0b964d-966d-4fcb-b0eb-016da43bc403">
<img width="679" alt="image" src="https://github.com/amtoine/nu-git-manager/assets/7041726/5298aef4-f1b8-4744-9e7f-6756b632e6bb">

**Comment by melMass** [comment] 2023-10-30 13:07
Ok I talked to @amtoine, the imports in the readme aren't up to date so I wasn't installing gm properly, my bad.

Now that I did it all works and I don't get any panic, I tried a few things to be sure.

I'm on  nushell 0.86.0  on `macOS Ventura 13.3.1`
In `config.nu`:

```nushell
use modules/nu-git-manager/nu-git-manager *
```
(this is just where I store my modules you path should be different)


@stormasm  Do you by any chance use custom locations for the cache or the store? (`GIT_REPOS_CACHE`, `GIT_REPOS_HOME`)

**Comment by stormasm** [comment] 2023-10-31 17:35
@melMass @amtoine Ok so I spent awhile going over all of this stuff again and going with the default configuration etc...

And the cache is now being created fine without crashing nushell...

I think we are good and you or I can close out this issue...

Thanks for your help...

I will continue to kick the tires and ask more questions 😄

**Comment by stormasm** [comment] 2023-10-31 17:49
> Ok I talked to @amtoine, the imports in the readme aren't up to date so I wasn't installing gm properly, my bad.
> 
> Now that I did it all works and I don't get any panic, I tried a few things to be sure.
> 
> I'm on nushell 0.86.0 on `macOS Ventura 13.3.1` In `config.nu`:
> 
> ```nushell
> use modules/nu-git-manager/nu-git-manager *
> ```
> 
> (this is just where I store my modules you path should be different)
> 
> @stormasm Do you by any chance use custom locations for the cache or the store? (`GIT_REPOS_CACHE`, `GIT_REPOS_HOME`)

No I am not setting either of those environment variables

**Comment by stormasm** [comment] 2023-10-31 17:58
Let me do some more work on my end chasing down possibly what is going on 😄

**Comment by amtoine** [comment] 2023-11-04 14:27
it turns out the issues comes from the build of @stormasm: it was in debug mode rather than in release mode :open_mouth: 

hopefully this will be catch in the future as we ask for the Nushell `version` in the bug report template :crossed_fingers: 

as this is not an issue with `nu-git-manager`, i'll close it.
thanks y'all for looking into this and finally cracking the nut :pray:

**Closed** 2023-11-04 15:19 UTC
Labels: bug, platform-specific, core
